# Generated by Django 4.2.6 on 2023-10-25 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camiseta',
            fields=[
                ('idCamiseta', models.IntegerField(primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CamisetaColor',
            fields=[
                ('idCamisetaColor', models.AutoField(primary_key=True, serialize=False)),
                ('imagenCamisetaColor', models.BinaryField()),
                ('idCamiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camiseta_color', to='core.camiseta')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('colorId', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreColor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('idConsecutivo', models.AutoField(primary_key=True, serialize=False)),
                ('valorCamiseta', models.FloatField()),
                ('valorEstampado', models.FloatField()),
                ('valorEstampar', models.FloatField(default=20000.0)),
                ('camisetaColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_factura', to='core.camisetacolor')),
            ],
        ),
        migrations.CreateModel(
            name='Estampado',
            fields=[
                ('idEstampado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('estampas', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('idTipoPersona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreTipoPersona', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('numero_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria'), ('TI', 'Tarjeta d identidad')], max_length=64)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=30, unique=True, verbose_name='Email')),
                ('numeroCelular', models.CharField(help_text='Ingrese un número de celular de 10 dígitos', max_length=10, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('tipo_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoPersona', to='core.tipopersona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.AutoField(primary_key=True, serialize=False)),
                ('detalleFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='core.detallefactura')),
                ('nombrePersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='estampado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_factura', to='core.estampado'),
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('idCatalogo', models.IntegerField(primary_key=True, serialize=False)),
                ('camisetaColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo', to='core.camisetacolor')),
                ('estampado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo', to='core.estampado')),
            ],
        ),
        migrations.AddField(
            model_name='camisetacolor',
            name='idColor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_camiseta', to='core.color'),
        ),
    ]
