# Generated by Django 4.2.6 on 2023-11-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='correo',
            new_name='email',
        ),
    ]
