# Generated by Django 4.2.6 on 2023-11-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numero_documento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
