# Generated by Django 4.2.6 on 2023-11-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_numero_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='estampado',
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria'), ('TI', 'Tarjeta de identidad')], max_length=64),
        ),
        migrations.DeleteModel(
            name='Catalogo',
        ),
        migrations.DeleteModel(
            name='Estampado',
        ),
    ]
