# Generated by Django 4.2.6 on 2023-11-26 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estampado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estampado',
            old_name='date_created',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='estampado',
            name='artista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
