# Generated by Django 4.2.6 on 2023-11-26 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estampado', '0002_rename_date_created_estampado_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estampado',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
