from .persona import Persona
from .tipoPersona import TipoPersona
from .camiseta import Camiseta
from .camisetaColor import CamisetaColor
from .catalogo import Catalogo
from .color import Color
from .detalleFactura import DetalleFactura
from .estampado import Estampado
from .factura import Factura
