# Generated by Django 4.2.6 on 2023-10-16 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('idTipoPersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoPersona', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('numero_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=30)),
                ('numeroCelular', models.IntegerField()),
                ('dirreccion', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=15)),
                ('tipo_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='authApp.tipopersona')),
            ],
        ),
    ]
