# Generated by Django 4.2.6 on 2023-10-16 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camiseta',
            fields=[
                ('idCamiseta', models.IntegerField(primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CamisetaColor',
            fields=[
                ('idCamisetaColor', models.IntegerField(primary_key=True, serialize=False)),
                ('imagenCamisetaColor', models.BinaryField()),
                ('idCamiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camiseta_color', to='authApp.camiseta')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('colorId', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreColor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('idConsecutivo', models.IntegerField(primary_key=True, serialize=False)),
                ('valorCamiseta', models.FloatField()),
                ('valorEstampado', models.FloatField()),
                ('valorEstampar', models.FloatField(default=20000.0)),
                ('camisetaColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_factura', to='authApp.camisetacolor')),
            ],
        ),
        migrations.CreateModel(
            name='Estampado',
            fields=[
                ('idEstampado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('estampas', models.BinaryField()),
            ],
        ),
        migrations.AlterField(
            model_name='tipopersona',
            name='idTipoPersona',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.IntegerField(primary_key=True, serialize=False)),
                ('detalleFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='authApp.detallefactura')),
                ('nombrePersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='authApp.persona')),
            ],
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='estampado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_factura', to='authApp.estampado'),
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('idCatalogo', models.IntegerField(primary_key=True, serialize=False)),
                ('camisetaColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo', to='authApp.camisetacolor')),
                ('estampado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo', to='authApp.estampado')),
            ],
        ),
        migrations.AddField(
            model_name='camisetacolor',
            name='idColor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_camiseta', to='authApp.color'),
        ),
    ]
