# Generated by Django 4.2.6 on 2023-10-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_camiseta_camisetacolor_color_detallefactura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camisetacolor',
            name='idCamisetaColor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='idConsecutivo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='idFactura',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
