# Generated by Django 4.2.6 on 2023-10-21 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_remove_persona_contraseña_persona_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('numero_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('tipo_documento', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=20, verbose_name='Name')),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=30, unique=True, verbose_name='Email')),
                ('numeroCelular', models.IntegerField(unique=True)),
                ('dirreccion', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('tipo_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoPersona', to='authApp.tipopersona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='factura',
            name='nombrePersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='authApp.user'),
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
