# Generated by Django 4.2.6 on 2023-10-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_user_alter_factura_nombrepersona_delete_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria'), ('TI', 'Tarjeta d identidad')], max_length=64),
        ),
    ]
