# Generated by Django 4.2.6 on 2023-10-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_alter_user_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numeroCelular',
            field=models.CharField(help_text='Ingrese un número de celular de 10 dígitos', max_length=10, unique=True),
        ),
    ]
