# Generated by Django 4.2.6 on 2023-10-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authApp', '0008_alter_user_nombre_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dirreccion',
            new_name='direccion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tipo_persona',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_user_permissions', related_query_name='user_user_permission', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cedula de ciudadanía'), ('CE', 'Cedula de extranjería'), ('TI', 'Tarjeta de identidad')], max_length=64),
        ),
    ]
