# Generated by Django 4.2.6 on 2023-10-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0009_rename_dirreccion_user_direccion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoPersona',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria'), ('TI', 'Tarjeta d identidad')], max_length=64),
        ),
    ]
