# Generated by Django 4.2.6 on 2023-10-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0010_delete_tipopersona_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('idTipoPersona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreTipoPersona', models.CharField(max_length=20)),
            ],
        ),
    ]
